-- Seed page_templates from src/data/reportContent.ts
-- 65 page definitions. Idempotent via ON CONFLICT (slug) DO NOTHING.
-- Step 2 of the new wizard reads this table to build the available-pages list
-- it sends to recommend-report-pages. Empty table = wizard fails at TOC stage.

INSERT INTO public.page_templates (slug, name, group_name, sub_group, default_order, is_custom)
VALUES
  ('executive-summary', 'Executive Summary', 'information', NULL, 0, false),
  ('roof-system', 'Roof System', 'exterior', NULL, 100, false),
  ('siding-cladding', 'Siding & Cladding', 'exterior', NULL, 101, false),
  ('windows', 'Windows', 'exterior', NULL, 102, false),
  ('exterior-doors', 'Exterior Doors', 'exterior', NULL, 103, false),
  ('gutters-downspouts', 'Gutters & Downspouts', 'exterior', NULL, 104, false),
  ('deck-patio', 'Deck & Patio', 'exterior', NULL, 105, false),
  ('driveway-walkways', 'Driveway & Walkways', 'exterior', NULL, 106, false),
  ('landscaping', 'Landscaping', 'exterior', NULL, 107, false),
  ('living-room', 'Living Room', 'interior-living', NULL, 200, false),
  ('dining-room', 'Dining Room', 'interior-living', NULL, 201, false),
  ('family-room', 'Family Room', 'interior-living', NULL, 202, false),
  ('home-office', 'Home Office', 'interior-living', NULL, 203, false),
  ('bonus-room', 'Bonus Room / Flex Space', 'interior-living', NULL, 204, false),
  ('primary-bedroom', 'Primary Bedroom', 'interior-bedrooms', NULL, 300, false),
  ('bedroom-2', 'Bedroom 2', 'interior-bedrooms', NULL, 301, false),
  ('bedroom-3', 'Bedroom 3', 'interior-bedrooms', NULL, 302, false),
  ('bedroom-4', 'Bedroom 4', 'interior-bedrooms', NULL, 303, false),
  ('primary-bathroom', 'Primary Bathroom', 'interior-bathrooms', NULL, 400, false),
  ('hall-bathroom', 'Hall Bathroom', 'interior-bathrooms', NULL, 401, false),
  ('powder-room', 'Powder Room', 'interior-bathrooms', NULL, 402, false),
  ('kitchen', 'Kitchen', 'interior-utility', NULL, 500, false),
  ('laundry-room', 'Laundry Room', 'interior-utility', NULL, 501, false),
  ('mudroom-entry', 'Mudroom & Entry', 'interior-utility', NULL, 502, false),
  ('pantry-storage', 'Pantry & Storage', 'interior-utility', NULL, 503, false),
  ('stairways-hallways', 'Stairways & Hallways', 'interior-utility', NULL, 504, false),
  ('basement', 'Basement', 'interior-unfinished', NULL, 600, false),
  ('attic', 'Attic', 'interior-unfinished', NULL, 601, false),
  ('garage', 'Garage', 'interior-unfinished', NULL, 602, false),
  ('primary-furnace', 'Primary Furnace', 'systems-hvac', NULL, 700, false),
  ('air-conditioning', 'Air Conditioning', 'systems-hvac', NULL, 701, false),
  ('insulation-ventilation', 'Insulation & Ventilation', 'systems-hvac', NULL, 702, false),
  ('electrical-panel', 'Electrical Panel', 'systems-mechanical', NULL, 800, false),
  ('plumbing-system', 'Plumbing System', 'systems-mechanical', NULL, 801, false),
  ('water-heater', 'Water Heater', 'systems-mechanical', NULL, 802, false),
  ('fireplace-chimney', 'Fireplace & Chimney', 'systems-mechanical', NULL, 803, false),
  ('foundation', 'Foundation', 'systems-mechanical', NULL, 804, false),
  ('refrigerator', 'Refrigerator', 'appliances', NULL, 900, false),
  ('range-oven', 'Range & Oven', 'appliances', NULL, 901, false),
  ('microwave', 'Microwave', 'appliances', NULL, 902, false),
  ('dishwasher', 'Dishwasher', 'appliances', NULL, 903, false),
  ('garbage-disposal', 'Garbage Disposal', 'appliances', NULL, 904, false),
  ('washer-dryer', 'Washer & Dryer', 'appliances', NULL, 905, false),
  ('range-hood', 'Range Hood', 'appliances', NULL, 906, false),
  ('fence-gate', 'Fence & Gate', 'exterior-structures', NULL, 1000, false),
  ('shed-outbuilding', 'Shed / Outbuilding', 'exterior-structures', NULL, 1001, false),
  ('outdoor-lighting', 'Outdoor Lighting', 'exterior-structures', NULL, 1002, false),
  ('irrigation-sprinklers', 'Irrigation & Sprinklers', 'exterior-structures', NULL, 1003, false),
  ('pool-spa', 'Pool & Spa', 'exterior-structures', NULL, 1004, false),
  ('sunroom-screened-porch', 'Sunroom / Screened Porch', 'interior-additional', NULL, 1100, false),
  ('media-room', 'Media Room', 'interior-additional', NULL, 1101, false),
  ('crawlspace', 'Crawlspace', 'interior-additional', NULL, 1102, false),
  ('workshop', 'Workshop', 'interior-additional', NULL, 1103, false),
  ('ductwork-ventilation', 'Ductwork & Ventilation', 'systems-additional', NULL, 1200, false),
  ('thermostat-smart-home', 'Thermostat & Smart Home', 'systems-additional', NULL, 1201, false),
  ('water-softener-filtration', 'Water Softener & Filtration', 'systems-additional', NULL, 1202, false),
  ('sump-pump', 'Sump Pump', 'systems-additional', NULL, 1203, false),
  ('septic-well', 'Septic & Well', 'systems-additional', NULL, 1204, false),
  ('solar-panels', 'Solar Panels', 'systems-additional', NULL, 1205, false),
  ('smoke-co-detectors', 'Smoke & CO Detectors', 'safety-detection', NULL, 1300, false),
  ('security-system', 'Security System', 'safety-detection', NULL, 1301, false),
  ('fire-extinguishers', 'Fire Extinguishers', 'safety-detection', NULL, 1302, false),
  ('radon-mitigation', 'Radon Mitigation', 'safety-detection', NULL, 1303, false),
  ('financial-roadmap', 'Financial Roadmap', 'strategy', NULL, 1400, false),
  ('action-plan', 'Action Plan', 'strategy', NULL, 1401, false)
ON CONFLICT (slug) DO NOTHING;
