-- HCR rebuild Phase 1 / M1: create daily_briefs.
--
-- Powers the Today's Brief card on Portal Home (Master Spec Section 4, ticket
-- C10 / [v1.22]). One row per property per day. Generated by the
-- daily-brief-cron edge function (built later in E1) at ~5 AM local time and
-- cached for the day. The whole point of this table is to avoid per-pageview
-- AI calls — the cron pays the model cost once a day and every portal visit
-- after that is a plain SELECT.
--
-- Tone-discipline note: brief_html and why_it_matters_html are the rendered
-- copy that lands in front of the client. The cron prompt enforces "no
-- em-dashes, no comparison anchors, no salesy language, word-based ratings
-- only" but the column itself imposes nothing — the editorial gate lives
-- upstream in the prompt and the consistency-check function (E5).
--
-- Cost discipline (Master Spec 5.8): when the cron finds zero actionable
-- signals for a property it writes a calm-day templated brief with
-- ai_model = 'template:calm_day'. That keeps idempotency intact (one row per
-- property per day) and keeps a calm day at literally zero AI spend.
--
-- This migration is idempotent — every object uses IF NOT EXISTS and policies
-- use DROP-IF-EXISTS / CREATE so re-running on a project that already has
-- the table (e.g. after a `migration repair`) is a no-op rather than an
-- error.

-- ── 1. Table ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.daily_briefs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- WHO/WHAT this brief is about. property_id is the operational key (the
  -- cron iterates properties, not users). client_user_id is denormalized
  -- here so the client-side RLS policy can do a single-column equality
  -- check without joining to properties on every read.
  property_id uuid NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
  client_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- WHEN. brief_date is the local calendar date the brief is for, NOT the
  -- timestamp the cron ran. Pairing with property_id in the unique
  -- constraint below is what makes the cron idempotent.
  brief_date date NOT NULL,

  -- WHAT lands on the page. brief_html is the headline + 1-2 sentence body
  -- shown in the Today's Brief card. why_it_matters_html is the optional
  -- expanded explainer revealed by the "Why this matters now" toggle
  -- ([v1.22]). Both are pre-rendered HTML — the renderer trusts them.
  brief_html text NOT NULL,
  why_it_matters_html text,

  -- WHY: machine-readable list of the signals that fed the brief. Drives
  -- the "Why this matters now" expand and is the audit trail for replay.
  -- Shape (per Master Spec 5.1.1):
  --   [{"type":"recurring_service_due","service_id":"...","days_overdue":3},
  --    {"type":"weather","forecast":"freeze warning Thursday"},
  --    {"type":"system_eol","system":"furnace","years_remaining":3}]
  source_signals jsonb NOT NULL DEFAULT '[]'::jsonb,

  -- WHICH model. Recorded per-row so we can A/B model swaps and replay an
  -- old brief against a new model without losing the lineage. Calm-day
  -- briefs use the sentinel 'template:calm_day' (no model call).
  ai_model text NOT NULL,

  -- WHEN the cron actually generated it (vs brief_date which is the date
  -- the brief is FOR).
  generated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),

  -- Idempotency anchor: re-running the cron for the same property on the
  -- same day must upsert, not duplicate. The cron uses ON CONFLICT
  -- (property_id, brief_date) DO UPDATE.
  UNIQUE (property_id, brief_date)
);

-- ── 2. Indexes ───────────────────────────────────────────────────────────
-- Both reads are "most recent brief for this {property|client}" — DESC on
-- brief_date pairs with the partition key so the planner can stop after one
-- row.

CREATE INDEX IF NOT EXISTS idx_daily_briefs_property_date
  ON public.daily_briefs (property_id, brief_date DESC);

CREATE INDEX IF NOT EXISTS idx_daily_briefs_client_date
  ON public.daily_briefs (client_user_id, brief_date DESC);

-- ── 3. RLS ───────────────────────────────────────────────────────────────
-- Three roles touch this table:
--   client       — reads their OWN briefs only (Portal Home card)
--   creator      — reads ALL briefs (admin role; any creator can preview
--                  any property's brief). This matches the codebase-wide
--                  pattern used by every other tenant table on this
--                  project: properties / reports / etc. all express
--                  creator access as has_role(auth.uid(), 'creator'),
--                  not as a per-property creator_id join.
--   service_role — the cron writes every row; no human ever inserts here
--
-- Spec adaptation: Master Spec 5.1.1 wrote the creator policy as
--   EXISTS (SELECT 1 FROM properties WHERE id = property_id AND creator_id = auth.uid())
-- but properties has no creator_id column — the actual ownership model
-- here is role-based. M2-M7 will use the same has_role() pattern.
--
-- The service-role policies use auth.jwt() ->> 'role' = 'service_role',
-- the canonical Supabase pattern (the service role key embeds that claim
-- in its JWT). This matches Master Spec 5.1.1 verbatim.

ALTER TABLE public.daily_briefs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Clients read own briefs" ON public.daily_briefs;
CREATE POLICY "Clients read own briefs"
  ON public.daily_briefs
  FOR SELECT
  USING (auth.uid() = client_user_id);

DROP POLICY IF EXISTS "Creators read all briefs" ON public.daily_briefs;
CREATE POLICY "Creators read all briefs"
  ON public.daily_briefs
  FOR SELECT
  USING (public.has_role(auth.uid(), 'creator'::public.app_role));

DROP POLICY IF EXISTS "Service role writes briefs" ON public.daily_briefs;
CREATE POLICY "Service role writes briefs"
  ON public.daily_briefs
  FOR INSERT
  WITH CHECK (auth.jwt() ->> 'role' = 'service_role');

DROP POLICY IF EXISTS "Service role updates briefs" ON public.daily_briefs;
CREATE POLICY "Service role updates briefs"
  ON public.daily_briefs
  FOR UPDATE
  USING (auth.jwt() ->> 'role' = 'service_role');
