// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { assertSupabaseConfig } from './project-ref';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Guard: refuse to construct a client pointed at the wrong Supabase project.
// A silent drift bricks the whole app; better to crash at import time with a
// clear message than to connect to the wrong database.
assertSupabaseConfig({ url: SUPABASE_URL, key: SUPABASE_PUBLISHABLE_KEY });

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
